name: CI

on: [push]

jobs:
  build-withcmake:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Run the build
      run: |
        sudo apt update
        sudo apt remove -y msodbcsql17 mysql-server mysql-server-5.7
        ./RaspiFullInstall.sh
      env:
        ACCEPT_EULA: Y

  build-aptcmake:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run the build, getting cmake from apt
      run: |
        #On this build, use apt cmake to check that works
        sudo rm /usr/local/bin/cmake*
        sudo apt purge --auto-remove cmake
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        sudo apt update
        sudo apt remove -y msodbcsql17 mysql-server mysql-server-5.7
        ./RaspiFullInstall.sh
        # Check cmake was installed, this errors if cmake not installed.
        dpkg -l cmake
      env:
        ACCEPT_EULA: Y
